-- ═══════════════════════════════════════════════════════
-- TABLA ai_memoria — Sistema de Compras IA · Mercado Limpio
-- Ejecutar en: https://supabase.com/dashboard/project/gjeyvbidomxzofcdycya/sql
-- ═══════════════════════════════════════════════════════

-- 1. Crear tabla
CREATE TABLE IF NOT EXISTS ai_memoria (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        TEXT NOT NULL DEFAULT 'nota',  -- 'aprendizaje' | 'parametro' | 'nota'
  clave       TEXT,                           -- slug opcional para actualizar (ej: 'ciclo_esponjas')
  contenido   TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Trigger para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ai_memoria_updated_at
  BEFORE UPDATE ON ai_memoria
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3. Habilitar Row Level Security
ALTER TABLE ai_memoria ENABLE ROW LEVEL SECURITY;

-- 4. Políticas: la key anon puede leer, insertar, actualizar y borrar
--    (es una app interna con PIN, no pública)
CREATE POLICY "anon_read"   ON ai_memoria FOR SELECT USING (true);
CREATE POLICY "anon_insert" ON ai_memoria FOR INSERT WITH CHECK (true);
CREATE POLICY "anon_update" ON ai_memoria FOR UPDATE USING (true);
CREATE POLICY "anon_delete" ON ai_memoria FOR DELETE USING (true);

-- 5. Insertar algunas notas iniciales para que la IA tenga contexto base
INSERT INTO ai_memoria (tipo, clave, contenido) VALUES
  ('parametro', 'negocio_desc',    'Mercado Limpio es una distribuidora de artículos de limpieza y hogar. Distribuye a comercios, almacenes y negocios. Principales categorías: esponjas, trapos, escobillones, rejillas, guantes, bolsas nylon, baldes.'),
  ('parametro', 'marcas_principales', 'Marcas principales: MAKE (premium), ROMYL (alternativa), ECO (económica), COTTON/FIBRAN (trapos), TE/TODOESPONJA/INT (marcas de esponja), MELLI/BIO BAG (bolsas nylon).'),
  ('parametro', 'ciclo_pedidos',   'Los vendedores cargan pedidos diariamente de lunes a viernes. El stock se repone según la demanda de los clientes. Los artículos que más rotan son esponjas de acero, fibras esponja y trapos de piso.');

-- Verificar
SELECT * FROM ai_memoria ORDER BY created_at;
